services:

  bws_container_admin:
    container_name: bws_container_admin
    build:
      context: .
      dockerfile: Dockerfile-dockeradmin
    #restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_volume:/data

  bws_db:
    container_name: bws_db
    build:
      context: .
      dockerfile: Dockerfile-bwsdb
    #restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bwsdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_volume:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d

  bws_db_admin:
    container_name: bws_db_admin
    build:
      context: .
      dockerfile: Dockerfile-bwsdbadmin
    #restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_volume:/var/lib/pgadmin

  bws_mq:
    container_name: bws_mq
    build:
      context: .
      dockerfile: Dockerfile-bwsmq
    #restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_volume:/var/lib/rabbitmq

  #bwsotelcollector:
  #  container_name: bwsotelcollector
  #  build:
  #    context: .
  #    dockerfile: Dockerfile-otelcollector
  #  #restart: always
  #  ports:
  #    - "18889:4317"
  #    - "18888:4318"
  #  volumes:
  #    - ./otel.conf/otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #    #- ./otelcollector_volume:/otelcol

  bws_grafana:
    container_name: bws_grafana
    build:
      context: .
      dockerfile: Dockerfile-bwsgrafana
    #restart: always
    ports:
      - 3000:3000
    volumes:
      - ./graf.conf/grafana.ini:/etc/grafana/grafana.ini
      - ./graf.conf/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./graf.conf/defaults.ini:/usr/share/grafana/conf/defaults.ini
      - ./grafana_volume:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - tempo
  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    command:
      -config.file=/etc/loki/local-config.yaml
  tempo:
    container_name: tempo
    image: grafana/tempo:1.2.0
    command: [ "-search.enabled=true", "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./graf.conf/tempo.yaml:/etc/tempo.yaml
    ports:
      - 8000:8000
      - 4317:4317

  bws_backend:
    container_name: bws_backend
    build:
      context: .
      dockerfile: Dockerfile-pythonfastapi
    #restart: always
    ports:
      - 8112:8111
    volumes:
      - ../src/Python.FastAPI:/SRC
      - /SRC/.venv
      - /SRC/__pycache__
    #depends_on:
    #  - bwsdb
    #  - bwsmq
    #logging:
    #  driver: loki
    #  options:
    #    loki-url: http://loki:3100/loki/api/v1/push
    command: uvicorn app:app --port 8111